### PR TITLE
Update Sonarr quality profiles with Bluray-576p

### PR DESCRIPTION
**Pull request by mikkelpetersen**
Fixes https://github.com/Dictionarry-Hub/profilarr/issues/136

### CODE REVIEW

**Comment by fgodin** [comment]
Fixed it for me. Thank you @mikkelpetersen

**Comment by willho01** [comment]
Forgive me, this is a stupid question, but how would i go about installing this on linux mint? or do i need to wait for it to be reviewed

**Comment by willho01** [comment]
Worked for me also

**Review by santiagosayshey — APPROVED** [review]
Approved, thanks for working on this!

**Comment by santiagosayshey** [comment]
thanks for verifying guys, will merge in now

**Pull request merged**
